export const starterIngredients = [
  { name: "All-Purpose Flour", nameDe: "Weizenmehl", category: "Flour" },
  { name: "Bread Flour", nameDe: "Brotmehl", category: "Flour" },
  { name: "Whole Wheat Flour", nameDe: "Vollkornmehl", category: "Flour" },
  { name: "Cake Flour", nameDe: "Kuchenmehl", category: "Flour" },
  { name: "Almond Flour", nameDe: "Mandelmehl", category: "Flour" },
  { name: "Coconut Flour", nameDe: "Kokosmehl", category: "Flour" },
  { name: "Rye Flour", nameDe: "Roggenmehl", category: "Flour" },
  { name: "Spelt Flour", nameDe: "Dinkelmehl", category: "Flour" },
  { name: "Granulated Sugar", nameDe: "Zucker", category: "Sweetener" },
  { name: "Brown Sugar", nameDe: "Brauner Zucker", category: "Sweetener" },
  { name: "Powdered Sugar", nameDe: "Puderzucker", category: "Sweetener" },
  { name: "Honey", nameDe: "Honig", category: "Sweetener" },
  { name: "Maple Syrup", nameDe: "Ahornsirup", category: "Sweetener" },
  { name: "Vanilla Sugar", nameDe: "Vanillezucker", category: "Sweetener" },
  { name: "Molasses", nameDe: "Melasse", category: "Sweetener" },
  { name: "Butter", nameDe: "Butter", category: "Dairy & Eggs" },
  { name: "Milk", nameDe: "Milch", category: "Dairy & Eggs" },
  { name: "Heavy Cream", nameDe: "Sahne", category: "Dairy & Eggs" },
  { name: "Sour Cream", nameDe: "Saure Sahne", category: "Dairy & Eggs" },
  { name: "Cream Cheese", nameDe: "Frischkäse", category: "Dairy & Eggs" },
  { name: "Buttermilk", nameDe: "Buttermilch", category: "Dairy & Eggs" },
  { name: "Yogurt", nameDe: "Joghurt", category: "Dairy & Eggs" },
  { name: "Eggs", nameDe: "Eier", category: "Dairy & Eggs" },
  { name: "Baking Powder", nameDe: "Backpulver", category: "Leavening" },
  { name: "Baking Soda", nameDe: "Natron", category: "Leavening" },
  { name: "Yeast", nameDe: "Hefe", category: "Leavening" },
  { name: "Instant Yeast", nameDe: "Trockenhefe", category: "Leavening" },
  { name: "Vegetable Oil", nameDe: "Pflanzenöl", category: "Oils & Fats" },
  { name: "Coconut Oil", nameDe: "Kokosöl", category: "Oils & Fats" },
  { name: "Olive Oil", nameDe: "Olivenöl", category: "Oils & Fats" },
  { name: "Margarine", nameDe: "Margarine", category: "Oils & Fats" },
  { name: "Vanilla Extract", nameDe: "Vanilleextrakt", category: "Flavoring" },
  { name: "Almond Extract", nameDe: "Mandelextrakt", category: "Flavoring" },
  { name: "Lemon Zest", nameDe: "Zitronenschale", category: "Flavoring" },
  { name: "Orange Zest", nameDe: "Orangenschale", category: "Flavoring" },
  { name: "Cocoa Powder", nameDe: "Kakaopulver", category: "Spices & Cocoa" },
  { name: "Cinnamon", nameDe: "Zimt", category: "Spices & Cocoa" },
  { name: "Nutmeg", nameDe: "Muskatnuss", category: "Spices & Cocoa" },
  { name: "Salt", nameDe: "Salz", category: "Spices & Cocoa" },
  {
    name: "Dark Chocolate",
    nameDe: "Zartbitterschokolade",
    category: "Chocolate",
  },
  {
    name: "Milk Chocolate",
    nameDe: "Vollmilchschokolade",
    category: "Chocolate",
  },
  {
    name: "White Chocolate",
    nameDe: "Weiße Schokolade",
    category: "Chocolate",
  },
  { name: "Walnuts", nameDe: "Walnüsse", category: "Nuts" },
  { name: "Almonds", nameDe: "Mandeln", category: "Nuts" },
  { name: "Hazelnuts", nameDe: "Haselnüsse", category: "Nuts" },
  { name: "Pecans", nameDe: "Pekannüsse", category: "Nuts" },
  { name: "Cornstarch", nameDe: "Speisestärke", category: "Thickeners" },
  { name: "Gelatin", nameDe: "Gelatine", category: "Thickeners" },
  { name: "Cream of Tartar", nameDe: "Weinstein", category: "Thickeners" },
  { name: "Poppy Seeds", nameDe: "Mohn", category: "Add-ins" },
  { name: "Coconut Flakes", nameDe: "Kokosflocken", category: "Add-ins" },
  { name: "Raisins", nameDe: "Rosinen", category: "Add-ins" },
  { name: "Sprinkles", nameDe: "Streusel", category: "Add-ins" },
];
